serial_number: 0000000000000
device_id: ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
device_id2: ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
signature: ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
mac: 00:00:00:00:00:00
username: myusername
password: mypassword
portal_url: http://domain.example.com/stalker_portal
time_zone: Europe/
token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
